# Generated by Django 4.2.7 on 2025-03-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse_admin',
            field=models.BooleanField(default=False, verbose_name='是否仓库管理员'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓名'),
        ),
    ]
