# Generated by Django 4.2.7 on 2025-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_warehouse_admin_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户'), (2, '企业用户'), (3, '超级管理员')], default=0, verbose_name='用户等级'),
        ),
    ]
