# Generated by Django 4.2.7 on 2025-03-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户'), (2, '企业用户'), (3, '超级管理员')], default=1, verbose_name='用户等级'),
        ),
    ]
