# Generated by Django 4.2.7 on 2025-03-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='仓库管理员')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='库区名称')),
                ('code', models.CharField(max_length=50, verbose_name='库区编码')),
                ('area_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='库区类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='warehouse.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '库区',
                'verbose_name_plural': '库区',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='库位名称')),
                ('code', models.CharField(max_length=50, verbose_name='库位编码')),
                ('location_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='库位类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_empty', models.BooleanField(default=True, verbose_name='是否为空')),
                ('max_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大容量')),
                ('current_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前容量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.warehousearea', verbose_name='所属库区')),
            ],
            options={
                'verbose_name': '库位',
                'verbose_name_plural': '库位',
                'ordering': ['area', 'code'],
                'unique_together': {('area', 'code')},
            },
        ),
    ]
