# Generated by Django 4.2.7 on 2025-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouselocation',
            name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='warehouselocation',
            name='max_capacity',
        ),
        migrations.AlterField(
            model_name='warehousearea',
            name='area_type',
            field=models.CharField(choices=[('normal', '普通区'), ('cold', '冷藏区'), ('dangerous', '危险品区'), ('valuable', '贵重品区')], default='normal', max_length=20, verbose_name='库区类型'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='is_empty',
            field=models.BooleanField(default=True, verbose_name='是否空置'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='location_type',
            field=models.CharField(choices=[('shelf', '货架'), ('ground', '地堆'), ('special', '特殊区')], default='shelf', max_length=20, verbose_name='库位类型'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='name',
            field=models.CharField(default='未命名库位', max_length=100, verbose_name='库位名称'),
        ),
    ]
