# Generated by Django 4.2.7 on 2025-03-06 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_remove_warehouselocation_current_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='报表标题')),
                ('report_date', models.DateField(verbose_name='报表日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报表描述')),
                ('data', models.JSONField(default=dict, verbose_name='报表数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='warehouse.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '报表',
                'verbose_name_plural': '报表',
                'ordering': ['-created_at'],
            },
        ),
    ]
