# Generated by Django 4.2.7 on 2025-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='key',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='报表唯一标识'),
        ),
    ]
