# Generated by Django 4.2.7 on 2025-03-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用数量')),
                ('locked_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='锁定数量')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('status', models.CharField(choices=[('normal', '正常'), ('locked', '锁定'), ('expired', '过期')], default='normal', max_length=20, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'ordering': ['-updated_time'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=50, unique=True, verbose_name='事务编号')),
                ('transaction_type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('transfer', '调拨'), ('return', '退货'), ('adjustment', '调整'), ('check', '盘点')], max_length=20, verbose_name='事务类型')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('before_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='操作前数量')),
                ('after_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='操作后数量')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='事务时间')),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联单号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '库存事务',
                'verbose_name_plural': '库存事务',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_code', models.CharField(max_length=50, unique=True, verbose_name='盘点单号')),
                ('check_type', models.CharField(choices=[('full', '全面盘点'), ('partial', '部分盘点')], max_length=20, verbose_name='盘点类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号')),
                ('system_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='系统数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际数量')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='差异数量')),
                ('status', models.CharField(choices=[('pending', '待盘点'), ('checked', '已盘点'), ('adjusted', '已调整')], max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='盘点时间')),
            ],
            options={
                'verbose_name': '盘点明细',
                'verbose_name_plural': '盘点明细',
                'ordering': ['stock_check', 'product'],
            },
        ),
    ]
