# Generated by Django 4.2.7 on 2025-03-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('product', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheckitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_items', to='warehouse.warehouselocation', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='stockcheckitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='product.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='stockcheckitem',
            name='stock_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcheck', verbose_name='盘点单'),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checks', to=settings.AUTH_USER_MODEL, verbose_name='盘点人'),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_checks', to='warehouse.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='warehouse.warehouselocation', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='product.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='warehouse.warehouselocation', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='product.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouse.warehouse', verbose_name='仓库'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcheckitem',
            unique_together={('stock_check', 'product', 'location', 'batch_number')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'location', 'product', 'batch_number')},
        ),
    ]
