# Generated by Django 4.2.7 on 2025-03-06 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_remove_warehouselocation_current_capacity_and_more'),
        ('product', '0001_initial'),
        ('inventory', '0003_transaction_inventory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_time'], 'verbose_name': '出入库记录', 'verbose_name_plural': '出入库记录'},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='after_quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='before_quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='规格/型号'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='个', max_length=20, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='规格/型号'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(default='个', max_length=20, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventories', to='product.product', verbose_name='品项'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='经手人'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_transactions', to='product.product', verbose_name='品项'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', '入库'), ('OUT', '出库')], max_length=10, verbose_name='事务类型'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'location', 'product')},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='locked_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
    ]
