# Generated by Django 4.2.7 on 2025-03-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouselocation_current_capacity_and_more'),
        ('inventory', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='期初库存'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计入库'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计出库'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='库存金额'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_inventories', to='warehouse.warehouselocation', verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存'),
        ),
    ]
